In [4]:
# Indexing and slicing
import numpy
arr = numpy.random.randint(1, 50, size=(6,4))

In [5]:
arr

array([[22, 15,  1, 35],
       [13, 48,  1, 40],
       [ 4, 45,  6, 37],
       [24, 48, 39,  5],
       [11, 13,  7, 13],
       [24, 35, 15, 11]], dtype=int32)

In [6]:
arr[0,2]

np.int32(1)

In [7]:
arr

array([[22, 15,  1, 35],
       [13, 48,  1, 40],
       [ 4, 45,  6, 37],
       [24, 48, 39,  5],
       [11, 13,  7, 13],
       [24, 35, 15, 11]], dtype=int32)

In [9]:
arr[0,2]

np.int32(1)

In [11]:
arr[0:5]

array([[22, 15,  1, 35],
       [13, 48,  1, 40],
       [ 4, 45,  6, 37],
       [24, 48, 39,  5],
       [11, 13,  7, 13]], dtype=int32)

In [ ]:
import array


arr[2, 2]

TypeError: 'module' object is not subscriptable